import { Box } from "@chakra-ui/react";
// app/faqs/page.jsx

// SEO Metadata
export const metadata = {
  title: "Kuza FAQs — Unit Trust, Pension & Account Opening | Kuza Asset Management",
  description:
    "Kuza Frequently Asked Questions — Complete answers on Unit Trust funds, Money Market & Fixed Income, Kuza Individual Pension Plan (IPP), Income Drawdown Fund, account opening steps, required documents, withdrawals, fees, custodians, trustees and taxes.",
  keywords: [
    "Kuza FAQs",
    "Kuza Unit Trust FAQs",
    "Kuza Pension FAQs",
    "Kuza Account Opening",
    "Kuza Money Market Fund",
    "Kuza Fixed Income Fund",
    "Kuza IPP",
    "Kuza Income Drawdown Fund",
    "Kuza client portal",
    "Kuza.Africa app",
    "how to open Kuza account",
    "Kuza withdrawal fees",
    "Kuza custodian trustee"
  ].join(", "),
};

export default function FAQsPage() {
  const faqJsonLd = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    "mainEntity": [
      // UNIT TRUST FAQs (1..18)
      {
        "@type": "Question",
        "name": "1. What is a unit trust fund?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "A Unit Trust Fund is a collective investment scheme that pools funds from multiple investors. These funds are then invested in a diversified portfolio of assets, which may include equities, interest-bearing securities, and other financial instruments. Investors in the Unit Trust Fund earn returns in the form of dividends, interest income, and/or capital gains, depending on the asset classes in which the fund is invested."
        }
      },
      {
        "@type": "Question",
        "name": "2. What is the Kuza Asset Management Unit Trust Scheme?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "The Kuza Unit Trust Scheme is an umbrella fund offering a variety of investment options through its five distinct funds:\n    i. Kuza Money Market (MMF) KES Fund\n    ii. Kuza Money Market (MMF) USD Fund\n    iii. Kuza Fixed Income Fund\n    iv. Kuza Momentum Special Fund\n    v. Kuza Shariah Momentum Special Fund\nEach of these funds address different investor needs and objectives, ranging from short-term liquidity to long term capital growth."
        }
      },
      {
        "@type": "Question",
        "name": "3. What is a Money Market Fund?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "A Money Market Fund is a collective investment scheme that pools investors' money to invest in short-term, interest-bearing instruments such as bank deposits, Treasury bills, Short-Term Bonds, Corporate Bonds and commercial papers. Investors in the fund are allocated units based on the value of their contributions, and they earn returns from the income generated by these investments."
        }
      },
      {
        "@type": "Question",
        "name": "4. What is the difference between the Fixed Income Fund and the Money Market Fund?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "The primary difference between the Money Market Fund (MMF) and the Fixed Income Fund (FIF) lies in the maturity profile of the underlying securities. The MMF invests in short-term securities, while the FIF focuses on longer-term fixed-income securities.\nThe MMF has a two-week lock-in period, meaning investors can withdraw funds after 14 days. In contrast, the FIF has a three-month lock-in period before the first  withdrawal is allowed."
        }
      },
      {
        "@type": "Question",
        "name": "5. Who can invest in the MMF USD?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "The Kuza USD Money Market Fund is available to all investors seeking to invest in USD. It’s a valuable option for those looking to diversify their portfolio and hedge against the Kenyan Shilling (KES) depreciation relative to the USD."
        }
      },
      {
        "@type": "Question",
        "name": "6. How can I keep track of my investment and monitor the fund’s performance?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "• The daily and effective annual yields of our Unit Trust funds are published in local newspapers.\n• You can also monitor your account’s performance by logging into our mobile app, ‘Kuza.Africa,’ available on both Google Playstore and Apple Appstore, or via our client portal at ‘client.kuza.africa.’\n• Additionally, we provide a password-protected monthly statement highlighting your account’s  performance for the previous month."
        }
      },
      {
        "@type": "Question",
        "name": "7. Who are the Kuza Unit Trust Fund Custodian and Trustee?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "• The Custodian of our Unit Trust Funds is KCB Bank Kenya.\n• The Trustee is Co-operative Bank Kenya."
        }
      },
      {
        "@type": "Question",
        "name": "8. Where does the Kuza Unit Trust funds invest my money?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "Kuza invests funds according to the guidelines outlined in the Capital Markets Authority’s approved Information Memorandum specific to each Unit Trust fund."
        }
      },
      {
        "@type": "Question",
        "name": "9. Is my capital secure in the Kuza Unit Trust Scheme?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "Kuza Asset Management is licensed by the Capital Markets Authority to operate as a fund manager, and our products are also licensed and regulated by the Capital Markets Authority.\nHypothetically, if Kuza were not there, your funds would remain safe and secure since our custodian, KCB Bank, holds all the funds. The funds will be available, or CMA will appoint another fund manager to continue managing your investments."
        }
      },
      {
        "@type": "Question",
        "name": "10. How is my interest calculated? Are my returns guaranteed?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "Interest in the MMF and FIF is calculated daily based on the fund’s yield and credited monthly. The individual fund’s returns are not guaranteed, as they are based on the performance of the underlying assets. Kuza focuses on low-risk investments that outperform benchmarks while maintaining capital preservation and offering high liquidity."
        }
      },
      {
        "@type": "Question",
        "name": "11. What is compounding of interest?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "Compounding interest refers to the reinvestment of the interest earned on your investment. This allows you to earn interest not only on your initial principal but also on the accumulated interest over time. This leads to exponential growth of your investment as the interest keeps building on itself. Interest compounding applies only to MMFs and the Fixed Income Fund, and we compound interest monthly."
        }
      },
      {
        "@type": "Question",
        "name": "12. Are top-ups mandatory in the Kuza Unit Trust Funds?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "No, top-ups are not mandatory but are highly encouraged. This is the only way to ensure you remain on track to achieve your investment goals."
        }
      },
      {
        "@type": "Question",
        "name": "13. When can I access my funds?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "• Unit Trust Funds are open-ended, meaning you can partially or wholly withdraw your funds after the lock-in period of the respective fund has elapsed.\n• We encourage regular top-ups to accelerate the growth of your investment and take advantage of the compounding effect over time."
        }
      },
      {
        "@type": "Question",
        "name": "14. What is the procedure for redeeming funds or making withdrawals from the Kuza Unit Trust Scheme?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "• You can initiate a withdrawal by specifying the amount you wish to withdraw via our mobile app or the client portal.\n• Alternatively, email our customer service team your withdrawal instructions.\n• Withdrawals can be either full or partial, and we process them within two working days."
        }
      },
      {
        "@type": "Question",
        "name": "15. Are there any charges that a client will incur when they withdraw from their unit trust account such as the Kuza money market fund, fixed income fund, momentum special fund, etc? (are there any redemption charges)?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "• There is a monthly withdrawal limit of KES 150000 for withdrawals via M-Pesa, with applicable M-Pesa transaction charges.\n• With bank transfers, you can enjoy the first two withdrawals per month free of charge. However, any additional withdrawals in the same month will incur a fee of KES 750 per transaction."
        }
      },
      {
        "@type": "Question",
        "name": "16. How long is the withdrawal processing period?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "• Funds will be received within one working day for withdrawals via M-Pesa.\n• For bank transfers, withdrawals will be processed within two working days."
        }
      },
      {
        "@type": "Question",
        "name": "17. Can proceeds from my investments be paid to a third party?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "Proceeds are only paid to the bank account or M-Pesa number registered during account opening."
        }
      },
      {
        "@type": "Question",
        "name": "18. Are taxes applicable to my investment?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "Yes, a 15% withholding tax is applied to income earned from Unit Trust funds."
        }
      },

      // PENSION FAQs (1..17)
      {
        "@type": "Question",
        "name": "PENSION FAQ 1. What is the Kuza Individual Pension Plan (IPP)?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "The Kuza Individual Pension Plan is a retirement savings scheme designed to help individuals save for their retirement by making regular contributions during their working years. This allows them to grow their retirement savings over time."
        }
      },
      {
        "@type": "Question",
        "name": "PENSION FAQ 2. What is the minimum contribution for the Kuza Individual Pension Plan?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "Members can contribute as little as KES 1000 per month."
        }
      },
      {
        "@type": "Question",
        "name": "PENSION FAQ 3. How do I join the Kuza Individual Pension Plan?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "To join, fill out the application form available on our website and attach copies of your ID/Passport, KRA PIN, and proof of bank. Once your first contribution is made, you will be issued a membership number."
        }
      },
      {
        "@type": "Question",
        "name": "PENSION FAQ 4. How do I transfer my contributions from another retirement benefits scheme to the Kuza Individual Pension Plan (IPP)?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "To transfer contributions from another registered retirement benefits scheme, you must fill out an exit form and select the option to transfer to the Kuza scheme."
        }
      },
      {
        "@type": "Question",
        "name": "PENSION FAQ 5. How are the Kuza Individual Pension Plan assets invested?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "The Kuza Individual Pension Plan operates under an Investment Policy Statement (IPS), which guides the Fund Manager in making investment decisions. The IPS has asset allocation limits that align with the Retirement Benefits Authority’s (RBA) allowable limits."
        }
      },
      {
        "@type": "Question",
        "name": "PENSION FAQ 6. What returns can I expect with the Kuza Individual Pension Plan?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "At Kuza Asset Management, our strategy focuses on maintaining a well-diversified portfolio and leveraging our expertise in alternative investments. This approach optimizes returns, enabling us to consistently offer above market average returns across all our products."
        }
      },
      {
        "@type": "Question",
        "name": "PENSION FAQ 7. Who are the service providers for the Kuza Individual Pension Plan?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "• Trustees: Kingsland Court\n• Administrators: Octagon Africa\n• Custodian: Equity Bank Kenya\n• Fund Manager: Kuza Asset Management Limited"
        }
      },
      {
        "@type": "Question",
        "name": "PENSION FAQ 8. What happens if I die or can no longer contribute to the Kuza Individual Pension Plan?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "The total fund value—including your contributions and investment returns – will be paid to your nominated beneficiaries in the event of your death. If you can no longer contribute, your earlier paid contributions will keep growing and can be accessed at retirement."
        }
      },
      {
        "@type": "Question",
        "name": "PENSION FAQ 9. Do I still need to join the Kuza Individual Pension Plan if I am also contributing to NSSF?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "Yes. NSSF contributions are relatively low and may need to be increased to support your retirement needs fully. Joining another pension scheme will help you grow your retirement savings more substantially."
        }
      },
      {
        "@type": "Question",
        "name": "PENSION FAQ 10. Do the contributions I make to the scheme earn an interest?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "Yes. Your contributions are invested as soon as they are received and start earning interest immediately. The total accumulated fund consists of your contributions and the earned investment return."
        }
      },
      {
        "@type": "Question",
        "name": "PENSION FAQ 11. How do I access my benefits upon retirement?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "Your benefit will be paid as a lump sum at retirement. You can then purchase an annuity or transfer your benefits into an income drawdown fund."
        }
      },
      {
        "@type": "Question",
        "name": "PENSION FAQ 12. Can I change my nominated beneficiary?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "You can change your nominated beneficiary or beneficiaries at any time by notifying us."
        }
      },
      {
        "@type": "Question",
        "name": "PENSION FAQ 13. What is an Income Drawdown Fund (IDD)?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "An Income Drawdown Fund is a retirement option that allows you to withdraw a regular income from your pension savings while keeping the remaining balance invested. It is ideal for retirees seeking flexibility in managing their retirement funds, but it requires careful planning to ensure your savings last throughout your retirement."
        }
      },
      {
        "@type": "Question",
        "name": "PENSION FAQ 14. Who is eligible to join the Income Drawdown Fund?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "Anyone over 50 is eligible to join the Income Drawdown Fund. The investment option is available to individuals who have accumulated pension savings and wish to start accessing their retirement funds while keeping the remaining balance invested."
        }
      },
      {
        "@type": "Question",
        "name": "PENSION FAQ 15. Who are the service providers for the Kuza Income Drawdown Fund Plan (IDD)?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "• Trustees: Kingsland Court\n• Administrators: Roberts Insurance Brokers Limited\n• Custodian: Equity Bank Kenya\n• Fund Manager: Kuza Asset Management Limited."
        }
      },
      {
        "@type": "Question",
        "name": "PENSION FAQ 16. What happens if I die while I have invested in the Kuza IDD?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "In the event of your death, the total fund value – including your principal and investment returns will be paid to your nominated beneficiaries."
        }
      },
      {
        "@type": "Question",
        "name": "PENSION FAQ 17. What is the minimum period one can invest in the Income Drawdown Fund?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "The Income Drawdown Fund has a minimum investment period of 10 years."
        }
      },

      // ACCOUNT OPENING FAQs
      {
        "@type": "Question",
        "name": "ACCOUNT OPENING FAQ 1. How do I open an account?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "We have two convenient options for opening a Money Market account with Kuza Asset Management:\nOption 1 for opening an account: Self-Registration via Kuza.Africa mobile App or Client Portal:\n    i. Visit the Kuza client portal at https://client.kuza.africa/self_registration?agent_no=00150 or Install the Kuza.Africa mobile app available on Google Play Store at https://play.google.com/store/apps/details?id=kuza.africa.kuza&hl=en&pli=1 for Android devices, or at https://apps.apple.com/ke/app/kuza-africa/id1662784344 for iPhones (can also get it on the App Store) then\n    ii. Follow the on-screen instructions to create your account.\n    iii. Complete the registration process by providing the necessary information.\n\nOption 2 for opening an account: Application Form Submission:\n    i. Alternatively, you can fill out our Unit Trust Application Form, available on our website https://kuza.africa/ and email it to customerservice@kuza.africa, along with a copy of your National ID, KRA PIN Certificate, and proof of bank (e.g., a copy of your recent bank statement, cancelled cheque, or a picture of the front side of your ATM card).\n    ii. Our team will process your account opening once all documents are submitted."
        }
      },
      {
        "@type": "Question",
        "name": "ACCOUNT OPENING FAQ 2. Can I open an account for a minor?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "Yes, a minor can have an account. To do so:\n    i. Download and fill out Our Unit Trust Application Form, which is available on our website, with the parent’sguardian’s and minor’s details.\n    ii. Attach the parent’s/guardian’s ID, KRA PIN certificate, one nominated bank account, and the minor’s birth certificate.\n    iii. Once the minor turns 18, they will have full control of their account."
        }
      },
      {
        "@type": "Question",
        "name": "ACCOUNT OPENING FAQ 3. What supporting documents are needed to create an Individual account?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "To open an individual account, the following documents are required:\n    i. Copy of Official Identification Document or Current Passport.\n    ii. Copy of PIN or Tax Exemption Certificate (where applicable).\n    iii. Proof of Banking details, such as an original cancelled cheque, copy of ATM Card, a bank Statement or a certified letter from the bank (not more than three months old)."
        }
      },
      {
        "@type": "Question",
        "name": "ACCOUNT OPENING FAQ 4. What supporting documents are needed to create a corporate account?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "To open a corporate account, please provide the following:\n    i. Founding Documents (Certificate of Incorporation or Partnership Agreement).\n    ii. A copy of your Memorandum and Articles of Association or an updated CR12.\n    iii. Proof of Resolution (minutes) authorizing the investment and designating representatives to act on behalf of the organization, including signing mandates and authorized signatories.\n    iv. A copy of the organization’s PIN Certificate or Tax Exemption Certificate (if applicable).\n    v. Proof of banking details, such as an original cancelled cheque, a copy of your ATM card, a bank statement, or a certified letter from your bank (not older than 3 months).\n    vi. A copy of the Official Identification Document (ID) or Current Passport for all signatories.\n    vii. A copy of the PIN Certificate for all signatories."
        }
      },
      {
        "@type": "Question",
        "name": "ACCOUNT OPENING FAQ 5. What supporting documents are needed to create a Joint account?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "To open a joint account, the following documents are required:\n    i. A copy of the Official Identification Document (ID) or Current Passport for all parties.\n    ii. A copy of the Tax PIN Certificate or Tax Exemption Certificate (if applicable) for all parties.\n    iii. Proof of bank such as a copy of your ATM card, a recent bank statement, or a certified letter from your bank (not older than 3 months)."
        }
      }
    ]
  };

  return (
    <Box as="section" bg="blue.300" py={4} > 
    <div className="container">

      {/* JSON-LD Structured Data */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }}
      />

      {/* Page Hero */}
      <section className="bottom-margin">
        <h1 className="hero">UNIT TRUST, PENSION & ACCOUNT OPENING — Frequently Asked Questions (FAQs)</h1>
        <p>
          Complete, client-facing Kuza FAQs covering Unit Trusts, Money Market & Fixed Income Funds, Kuza Individual Pension Plan (IPP), Income Drawdown Fund, and account opening procedures & document requirements.
        </p>
      </section>

      {/* UNIT TRUST FAQs */}
      <section className="bottom-margin">
        <h2>UNIT TRUST Frequently Asked Questions (FAQs)</h2>

        <h3 className="question">1. What is a unit trust fund?</h3>
        <p className="answer">A Unit Trust Fund is a collective investment scheme that pools funds from multiple investors. These funds are then invested in a diversified portfolio of assets, which may include equities, interest-bearing securities, and other financial instruments. Investors in the Unit Trust Fund earn returns in the form of dividends, interest income, and/or capital gains, depending on the asset classes in which the fund is invested.</p>

        <h3 className="question">2. What is the Kuza Asset Management Unit Trust Scheme?</h3>
        <p className="answer">
          The Kuza Unit Trust Scheme is an umbrella fund offering a variety of investment options through its five distinct funds:
          <br/>i. Kuza Money Market (MMF) KES Fund
          <br/>ii. Kuza Money Market (MMF) USD Fund
          <br/>iii. Kuza Fixed Income Fund
          <br/>iv. Kuza Momentum Special Fund
          <br/>v. Kuza Shariah Momentum Special Fund
          <br/>Each of these funds address different investor needs and objectives, ranging from short-term liquidity to long term capital growth.
        </p>

        <h3 className="question">3. What is a Money Market Fund?</h3>
        <p className="answer">A Money Market Fund is a collective investment scheme that pools investors' money to invest in short-term, interest-bearing instruments such as bank deposits, Treasury bills, Short-Term Bonds, Corporate Bonds and commercial papers. Investors in the fund are allocated units based on the value of their contributions, and they earn returns from the income generated by these investments.</p>

        <h3 className="question">4. What is the difference between the Fixed Income Fund and the Money Market Fund?</h3>
        <p className="answer">The primary difference between the Money Market Fund (MMF) and the Fixed Income Fund (FIF) lies in the maturity profile of the underlying securities. The MMF invests in short-term securities, while the FIF focuses on longer-term fixed-income securities.
        <br/>The MMF has a two-week lock-in period, meaning investors can withdraw funds after 14 days. In contrast, the FIF has a three-month lock-in period before the first  withdrawal is allowed.</p>

        <h3 className="question">5. Who can invest in the MMF USD?</h3>
        <p className="answer">The Kuza USD Money Market Fund is available to all investors seeking to invest in USD. It’s a valuable option for those looking to diversify their portfolio and hedge against the Kenyan Shilling (KES) depreciation relative to the USD.</p>

        <h3 className="question">6. How can I keep track of my investment and monitor the fund’s performance?</h3>
        <div className="answer">
          <ul>
            <li>The daily and effective annual yields of our Unit Trust funds are published in local newspapers.</li>
            <li>You can also monitor your account’s performance by logging into our mobile app, ‘Kuza.Africa,’ available on both Google Playstore and Apple Appstore, or via our client portal at ‘client.kuza.africa.’</li>
            <li>Additionally, we provide a password-protected monthly statement highlighting your account’s  performance for the previous month.</li>
          </ul>
        </div>

        <h3 className="question">7. Who are the Kuza Unit Trust Fund Custodian and Trustee?</h3>
        <div className="answer">
          <ul>
            <li>The Custodian of our Unit Trust Funds is KCB Bank Kenya.</li>
            <li>The Trustee is Co-operative Bank Kenya.</li>
          </ul>
        </div>

        <h3 className="question">8. Where does the Kuza Unit Trust funds invest my money?</h3>
        <p className="answer">Kuza invests funds according to the guidelines outlined in the Capital Markets Authority’s approved Information Memorandum specific to each Unit Trust fund.</p>

        <h3 className="question">9. Is my capital secure in the Kuza Unit Trust Scheme?</h3>
        <p className="answer">Kuza Asset Management is licensed by the Capital Markets Authority to operate as a fund manager, and our products are also licensed and regulated by the Capital Markets Authority.
        <br/>Hypothetically, if Kuza were not there, your funds would remain safe and secure since our custodian, KCB Bank, holds all the funds. The funds will be available, or CMA will appoint another fund manager to continue managing your investments.</p>

        <h3 className="question">10. How is my interest calculated? Are my returns guaranteed?</h3>
        <p className="answer">Interest in the MMF and FIF is calculated daily based on the fund’s yield and credited monthly. The individual fund’s returns are not guaranteed, as they are based on the performance of the underlying assets. Kuza focuses on low-risk investments that outperform benchmarks while maintaining capital preservation and offering high liquidity.</p>

        <h3 className="question">11. What is compounding of interest?</h3>
        <p className="answer">Compounding interest refers to the reinvestment of the interest earned on your investment. This allows you to earn interest not only on your initial principal but also on the accumulated interest over time. This leads to exponential growth of your investment as the interest keeps building on itself. Interest compounding applies only to MMFs and the Fixed Income Fund, and we compound interest monthly.</p>

        <h3 className="question">12. Are top-ups mandatory in the Kuza Unit Trust Funds?</h3>
        <p className="answer">No, top-ups are not mandatory but are highly encouraged. This is the only way to ensure you remain on track to achieve your investment goals.</p>

        <h3 className="question">13. When can I access my funds?</h3>
        <div className="answer">
          <ul>
            <li>Unit Trust Funds are open-ended, meaning you can partially or wholly withdraw your funds after the lock-in period of the respective fund has elapsed.</li>
            <li>We encourage regular top-ups to accelerate the growth of your investment and take advantage of the compounding effect over time.</li>
          </ul>
        </div>

        <h3 className="question">14. What is the procedure for redeeming funds or making withdrawals from the Kuza Unit Trust Scheme?</h3>
        <div className="answer">
          <ul>
            <li>You can initiate a withdrawal by specifying the amount you wish to withdraw via our mobile app or the client portal.</li>
            <li>Alternatively, email our customer service team your withdrawal instructions.</li>
            <li>Withdrawals can be either full or partial, and we process them within two working days.</li>
          </ul>
        </div>

        <h3 className="question">15. Are there any charges that a client will incur when they withdraw from their unit trust account such as the Kuza money market fund, fixed income fund, momentum special fund, etc? (are there any redemption charges)?</h3>
        <div className="answer">
          <ul>
            <li>There is a monthly withdrawal limit of KES 150000 for withdrawals via M-Pesa, with applicable M-Pesa transaction charges.</li>
            <li>With bank transfers, you can enjoy the first two withdrawals per month free of charge. However, any additional withdrawals in the same month will incur a fee of KES 750 per transaction.</li>
          </ul>
        </div>

        <h3 className="question">16. How long is the withdrawal processing period?</h3>
        <div className="answer">
          <ul>
            <li>Funds will be received within one working day for withdrawals via M-Pesa.</li>
            <li>For bank transfers, withdrawals will be processed within two working days.</li>
          </ul>
        </div>

        <h3 className="question">17. Can proceeds from my investments be paid to a third party?</h3>
        <p className="answer">Proceeds are only paid to the bank account or M-Pesa number registered during account opening.</p>

        <h3 className="question">18. Are taxes applicable to my investment?</h3>
        <p className="answer">Yes, a 15% withholding tax is applied to income earned from Unit Trust funds.</p>
      </section>

      {/* PENSION FAQs */}
      <section className="bottom-margin">
        <h2>PENSION FAQs</h2>

        <h3 className="question">1. What is the Kuza Individual Pension Plan (IPP)?</h3>
        <p className="answer">The Kuza Individual Pension Plan is a retirement savings scheme designed to help individuals save for their retirement by making regular contributions during their working years. This allows them to grow their retirement savings over time.</p>

        <h3 className="question">2. What is the minimum contribution for the Kuza Individual Pension Plan?</h3>
        <p className="answer">Members can contribute as little as KES 1000 per month.</p>

        <h3 className="question">3. How do I join the Kuza Individual Pension Plan?</h3>
        <p className="answer">To join, fill out the application form available on our website and attach copies of your ID/Passport, KRA PIN, and proof of bank. Once your first contribution is made, you will be issued a membership number.</p>

        <h3 className="question">4. How do I transfer my contributions from another retirement benefits scheme to the Kuza Individual Pension Plan (IPP)?</h3>
        <p className="answer">To transfer contributions from another registered retirement benefits scheme, you must fill out an exit form and select the option to transfer to the Kuza scheme.</p>

        <h3 className="question">5. How are the Kuza Individual Pension Plan assets invested?</h3>
        <p className="answer">The Kuza Individual Pension Plan operates under an Investment Policy Statement (IPS), which guides the Fund Manager in making investment decisions. The IPS has asset allocation limits that align with the Retirement Benefits Authority’s (RBA) allowable limits.</p>

        <h3 className="question">6. What returns can I expect with the Kuza Individual Pension Plan?</h3>
        <p className="answer">At Kuza Asset Management, our strategy focuses on maintaining a well-diversified portfolio and leveraging our expertise in alternative investments. This approach optimizes returns, enabling us to consistently offer above market average returns across all our products.</p>

        <h3 className="question">7. Who are the service providers for the Kuza Individual Pension Plan?</h3>
        <div className="answer">
          <ul>
            <li>Trustees: Kingsland Court</li>
            <li>Administrators: Octagon Africa</li>
            <li>Custodian: Equity Bank Kenya</li>
            <li>Fund Manager: Kuza Asset Management Limited</li>
          </ul>
        </div>

        <h3 className="question">8. What happens if I die or can no longer contribute to the Kuza Individual Pension Plan?</h3>
        <p className="answer">The total fund value—including your contributions and investment returns – will be paid to your nominated beneficiaries in the event of your death. If you can no longer contribute, your earlier paid contributions will keep growing and can be accessed at retirement.</p>

        <h3 className="question">9. Do I still need to join the Kuza Individual Pension Plan if I am also contributing to NSSF?</h3>
        <p className="answer">Yes. NSSF contributions are relatively low and may need to be increased to support your retirement needs fully. Joining another pension scheme will help you grow your retirement savings more substantially.</p>

        <h3 className="question">10. Do the contributions I make to the scheme earn an interest?</h3>
        <p className="answer">Yes. Your contributions are invested as soon as they are received and start earning interest immediately. The total accumulated fund consists of your contributions and the earned investment return.</p>

        <h3 className="question">11. How do I access my benefits upon retirement?</h3>
        <p className="answer">Your benefit will be paid as a lump sum at retirement. You can then purchase an annuity or transfer your benefits into an income drawdown fund.</p>

        <h3 className="question">12. Can I change my nominated beneficiary?</h3>
        <p className="answer">You can change your nominated beneficiary or beneficiaries at any time by notifying us.</p>

        <h3 className="question">13. What is an Income Drawdown Fund (IDD)?</h3>
        <p className="answer">An Income Drawdown Fund is a retirement option that allows you to withdraw a regular income from your pension savings while keeping the remaining balance invested. It is ideal for retirees seeking flexibility in managing their retirement funds, but it requires careful planning to ensure your savings last throughout your retirement.</p>

        <h3 className="question">14. Who is eligible to join the Income Drawdown Fund?</h3>
        <p className="answer">Anyone over 50 is eligible to join the Income Drawdown Fund. The investment option is available to individuals who have accumulated pension savings and wish to start accessing their retirement funds while keeping the remaining balance invested.</p>

        <h3 className="question">15. Who are the service providers for the Kuza Income Drawdown Fund Plan (IDD)?</h3>
        <div className="answer">
          <ul>
            <li>Trustees: Kingsland Court</li>
            <li>Administrators: Roberts Insurance Brokers Limited</li>
            <li>Custodian: Equity Bank Kenya</li>
            <li>Fund Manager: Kuza Asset Management Limited.</li>
          </ul>
        </div>

        <h3 className="question">16. What happens if I die while I have invested in the Kuza IDD?</h3>
        <p className="answer">In the event of your death, the total fund value – including your principal and investment returns will be paid to your nominated beneficiaries.</p>

        <h3 className="question">17. What is the minimum period one can invest in the Income Drawdown Fund?</h3>
        <p className="answer">The Income Drawdown Fund has a minimum investment period of 10 years.</p>
      </section>

      {/* ACCOUNT OPENING FAQs */}
      <section className="bottom-margin">
        <h2>ACCOUNT OPENING FAQs</h2>

        <h3 className="question">1. How do I open an account?</h3>
        <p className="answer">
          We have two convenient options for opening a Money Market account with Kuza Asset Management:
          <br/>
          <strong>Option 1 for opening an account: Self-Registration via Kuza.Africa mobile App or Client Portal:</strong>
          <br/>i. Visit the Kuza client portal at <a href="https://client.kuza.africa/self_registration?agent_no=00150">Kuza client portal</a> or Install the Kuza.Africa mobile app available on Google Play Store at <a href="https://play.google.com/store/apps/details?id=kuza.africa.kuza&hl=en&pli=1">https://play.google.com/store/apps/details?id=kuza.africa.kuza&hl=en&pli=1</a> for Android devices, or at <a href="https://apps.apple.com/ke/app/kuza-africa/id1662784344">https://apps.apple.com/ke/app/kuza-africa/id1662784344</a> for iPhones (can also get it on the App Store) then
          <br/>ii. Follow the on-screen instructions to create your account.
          <br/>iii. Complete the registration process by providing the necessary information.
          <br/><br/>
          <strong>Option 2 for opening an account: Application Form Submission:</strong>
          <br/>i. Alternatively, you can fill out our Unit Trust Application Form, available on our website <a href="https://kuza.africa/">https://kuza.africa/</a> and email it to <a href="mailto:customerservice@kuza.africa">customerservice@kuza.africa</a>, along with a copy of your National ID, KRA PIN Certificate, and proof of bank (e.g., a copy of your recent bank statement, cancelled cheque, or a picture of the front side of your ATM card).
          <br/>ii. Our team will process your account opening once all documents are submitted.
        </p>

        <h3 className="question">2. Can I open an account for a minor?</h3>
        <p className="answer">Yes, a minor can have an account. To do so:
          <br/>i. Download and fill out Our Unit Trust Application Form, which is available on our website, with the parent’sguardian’s and minor’s details.
          <br/>ii. Attach the parent’s/guardian’s ID, KRA PIN certificate, one nominated bank account, and the minor’s birth certificate.
          <br/>iii. Once the minor turns 18, they will have full control of their account.
        </p>

        <h3 className="question">3. What supporting documents are needed to create an Individual account?</h3>
        <p className="answer">To open an individual account, the following documents are required:
          <br/>i. Copy of Official Identification Document or Current Passport.
          <br/>ii. Copy of PIN or Tax Exemption Certificate (where applicable).
          <br/>iii. Proof of Banking details, such as an original cancelled cheque, copy of ATM Card, a bank Statement or a certified letter from the bank (not more than three months old).
        </p>

        <h3 className="question">4. What supporting documents are needed to create a corporate account?</h3>
        <p className="answer">To open a corporate account, please provide the following:
          <br/>i. Founding Documents (Certificate of Incorporation or Partnership Agreement).
          <br/>ii. A copy of your Memorandum and Articles of Association or an updated CR12.
          <br/>iii. Proof of Resolution (minutes) authorizing the investment and designating representatives to act on behalf of the organization, including signing mandates and authorized signatories.
          <br/>iv. A copy of the organization’s PIN Certificate or Tax Exemption Certificate (if applicable).
          <br/>v. Proof of banking details, such as an original cancelled cheque, a copy of your ATM card, a bank statement, or a certified letter from your bank (not older than 3 months).
          <br/>vi. A copy of the Official Identification Document (ID) or Current Passport for all signatories.
          <br/>vii. A copy of the PIN Certificate for all signatories.
        </p>

        <h3 className="question">5. What supporting documents are needed to create a Joint account?</h3>
        <p className="answer">To open a joint account, the following documents are required:
          <br/>i. A copy of the Official Identification Document (ID) or Current Passport for all parties.
          <br/>ii. A copy of the Tax PIN Certificate or Tax Exemption Certificate (if applicable) for all parties.
          <br/>iii. Proof of bank such as a copy of your ATM card, a recent bank statement, or a certified letter from your bank (not older than 3 months).
        </p>
      </section>

      {/* CTA */}

      <div className="centerButton" >
          <a className="link_button" href="https://client.kuza.africa/self_registration?agent_no=00150">Create Account to Invest</a>
        </div>
        
    </div>
    </Box>
  );
}
